trigger:
  batch: true
  branches:
    include:
    - main
    - develop
    - release/*
    - feature/*
    - bugfix/*
    - hotfix/*
#    - refs/tags/*
  paths:
    exclude:
    - docs/*
    - wiki/*

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: templates/templates
      ref: dotnetcli

steps:
# Check out the code and keep the token so we can tag the repository
- checkout: self
  persistCredentials: true

- template: library-template.yaml@templates
# NB Override parameters here as needed
  parameters:
#    solution: '**/*.sln'
#    buildPlatform: 'Any CPU'
#    buildConfiguration: 'Release'
    nugetFeed: '33ee36b3-29ec-4a24-9150-ff4a3fcfcbfe'
    testProjects: '**/*.sln'
#    testFilter: '(TestCategory!=Integration)&(TestCategory!=Smoke)'
#    testSettings: 'coverlet.runsettings'
    publishPackages: true
    codeCoverage: true
    gitTag: false